$(function(){
	//一、账号登录
	//1.用户名验证
	//获得焦点时（包括再次获得焦点）
	$(".inputs").focus(function(){
		//删除on
		$(this).removeClass('on');
		//默认提示信息消失
		$('.p1').hide();
		//进入提示图标出现
		$(".n1").show();
		//错号消失
		$(".l1").hide();
		//提示为空红色信息消失
		$("span").hide();
	});
	//失去焦点时
	$('.inputs').blur(function(){
		//判断是否为空
		if($(this).val()==""){
			$(this).addClass('on');
			//默认提示出现
			$('.p1').show();
			//进入提示图标消失
			$(".n1").hide();
			//错号出现
			$(".l1").show();
			//提示为空红色信息出现
			$(".blank1").show().siblings("span").hide();
		}
		//判断是否输入正确
		else{
			var userCheck=cellPhone($(this).val());
			if(userCheck==false){
				$(this).addClass('on');
				//错号出现
				$(".l1").show();
				$(".wrong").show().siblings("span").hide();
			}
		}
	});
	//2.密码验证
	//获得焦点时（包括再次获得焦点）
	$(".pass").focus(function(){
		$(this).removeClass('on');
		//默认提示信息消失
		$('.p2').hide();
		//进入提示图标出现
		$(".n2").show();
		//错号消失
		$(".l2").hide();
		//提示为空红色信息消失
		$(".blank2").hide();
	});
	//失去焦点时
	$('.pass').blur(function(){
		//判断是否为空
		if($(this).val()==""){
			$(this).addClass('on');
			//默认提示出现
			$('.p2').show();
			//进入提示图标消失
			$(".n2").hide();
			//错号出现
			$(".l2").show();
			//提示为空红色信息出现
			$(".blank2").show();
		}
	});
	//3.验证码验证
	//获得焦点时（包括再次获得焦点）
	$(".checks").focus(function(){
		$(this).removeClass('on');
		//默认提示信息消失
		$('.p3').hide();
		//提示为空红色信息消失
		$(".blank3").hide();
	});
	//失去焦点时
	$('.checks').blur(function(){
		//判断是否为空
		if($(this).val()==""){
			$(this).addClass('on');
			//默认提示出现
			$('.p3').show();
			//提示为空红色信息出现
			$(".blank3").show();
		}
	});
	//二、手机登录
		//1.用户名验证
	//获得焦点时（包括再次获得焦点）
	$(".inputs4").focus(function(){
		//删除on
		$(this).removeClass('on');
		//默认提示信息消失
		$('.p4').hide();
		//错号消失
		$(".l4").hide();
		//提示为空红色信息消失
		$("span").hide();
	});
	//失去焦点时
	$('.inputs4').blur(function(){
		//判断是否为空
		if($(this).val()==""){
			$(this).addClass('on');
			//默认提示出现
			$('.p4').show();
			//进入提示图标消失
			//错号出现
			$(".l4").show();
			//提示为空红色信息出现
			$(".blank4").show().siblings("span").hide();
		}
		//判断是否输入正确
		else{
			var userCheck=cellPhone($(this).val());
			if(userCheck==false){
				$(this).addClass('on');
				//错号出现
				$(".l4").show();
				$(".wrong4").show().siblings("span").hide();
			}
		}
	});
	//2.验证码验证
	//获得焦点时（包括再次获得焦点）
	$(".checks5").focus(function(){
		$(this).removeClass('on');
		//默认提示信息消失
		$('.p5').hide();
		//提示为空红色信息消失
		$(".blank5").hide();
	});
	//失去焦点时
	$('.checks5').blur(function(){
		//判断是否为空
		if($(this).val()==""){
			$(this).addClass('on');
			//默认提示出现
			$('.p5').show();
			//提示为空红色信息出现
			$(".blank5").show();
		}
	});
	

	//点击切换显示
	$('.titbox .phonel').click(function(){
		$(this).addClass('show').removeClass('hide');
		$('.userl').addClass('hide').removeClass('show');
		$('.one').hide();
		$('.two').show();
	});
	$('.titbox .userl').click(function(){
		$(this).addClass('show').removeClass('hide');
		$('.phonel').addClass('hide').removeClass('show');
		$('.one').show();
		$('.two').hide();
	});

	//点击切换显示
	$('.ewm').click(function(){
		$(this).hide();
		$('.form').show();
		$('.formbox').hide();
		$('.ewmbox').show();
	});
	$('.form').click(function(){
		$(this).hide();
		$('.ewm').show();
		$('.formbox').show();
		$('.ewmbox').hide();
	});

});